### ISSUE TITLE
Program contains incorrect schema

### ISSUE THREAD

**Issue by vinnividivicci** [DynamoDS/RevitTestFramework#1]
Hello and thanks for making this library open-source! It promises to help us create more reliable Revit Add-ins.

I have run into this issue:
![screenshot_060514_102349_am](https://cloud.githubusercontent.com/assets/591242/3188874/c38aa26a-ecbe-11e3-85b7-5dffbed43ade.jpg)

This happens after installing the framework from the .exe in the ```RevitTestFramework\tools\Output``` folder and trying to run the ```SampleTests.dll```.

I have verified that the ```empty.rfa``` file is in the correct year version for the version of Revit I am testing with, although I had to upgrade the ```empty.rfa``` and ```brick.rfa``` files that come with the source (they seemed to be in 2013 format), but it stills throw that error.

Also created brand-new versions of those files based off of the Metric Mass Family Template and it gives the same error.

Here is a screenshot of my settings:
![screenshot_060514_104125_am](https://cloud.githubusercontent.com/assets/591242/3188962/7af435e2-ecbf-11e3-824a-945721acc9fe.jpg)

The ```\2015``` does contain the ```empty.rfa``` and ```bricks.rfa``` files so that's not the problem.

Thanks :smile:

**Comment by vinnividivicci** [comment]
I'm still getting this error with the latest branch of 2015...

**Comment by ikeough** [comment]
@vinnividivicci I just figured this out because I got the same. Apparently, Revit journal files don't like it if the path to your .rvt file has spaces in it. It chops the path name at the first space and tries to open that as a Revit file. Unfortunately, I can't really control this. It's part of the journal framework. For now, you'll have to specify Revit files that are in a directory with no spaces in the name.
